model_type: "FastAI"
model_local_threshold: 0.5
model_global_threshold: 3
model_path: "./fastaimodel"
model_name: "rnd1to7_stg2-rn50.pkl"
hls_stream_type: "LiveHLS"
hls_polling_interval: 60
hls_hydrophone_id: "rpi_orcasound_lab"
upload_to_azure: True
delete_local_wavs: True